### ISSUE TITLE
Sum Notation

### ISSUE THREAD

**Issue by srush** [namedtensor/notation#1]
Yoav notes that $\sum_{time} A$ is a bit counterintuitive. His expectation would be $\sum_{time:i} A_{time:i}$. I wonder if there is different notation that conveys more that it is a reduction?

**Comment by davidweichiang** [comment]
I like $\sum_{time} A$ personally, but I'm curious if @yoavg would like $\sum A_{time}$ better under the "named and numbered indices" alternative. Here $\sum$ would be define to always sum over all numbered indices.

**Comment by srush** [comment]
Haha actually @yoavartzi ! Next step will be "Named Faculty Notation" for NLP professor disambiguition.

**Comment by srush** [comment]
Lillian suggested that in statistics they use a dot notation for sum <img src="https://latex.codecogs.com/gif.latex?A_{\bullet}" />. We could have a sum notation like that <img src="https://latex.codecogs.com/gif.latex?A_{\mathsf{time}:\bullet}"/> , actually kind of nice.

**Comment by srush** [comment]
![image](https://user-images.githubusercontent.com/35882/100904398-fda22c00-3494-11eb-99eb-0ed6821d29d1.png)

**Comment by davidweichiang** [comment]
Oh, well I definitely want to know what @yoavg thinks too!

The dot notation is nice but it makes summation into a "privileged" operation and I like the fact that our notation is currently pretty generic.

**Comment by craffel** [comment]
I was confused by this in the reductions section I think for two reasons:
1) You named the axis in the reduction example "i" and the summation index "x" but typical convention is that the summation index is "i" (e.g. \sum_{i = 1}^N x_i or whatever). This is true in various other places, e.g. you use conventally-index names i, j, k for axes names under "Matrices"
2) The "colon" syntax frequently trips me up. Python convention is that : denotes a range when indexing. When I see something like A_{i:x} I immediately think "indices i to x" not "index x on axis i".

For 1), any reason not to just keep using foo/bar/etc? It would make it more consistent with the rest of the doc.

For 2), I don't have any obvious suggestions but just wanted to flag it.

**Comment by davidweichiang** [comment]
1) I actually had used "a" as the generic index name for a long time and then changed it to "i" fairly late. I personally feel that the similarity between index name "i" (in sans-serif) and index variable "i" (in italics) is not harmful (it's kind of like https://en.wikipedia.org/wiki/Abstract_index_notation) but it's really helpful to hear other people's impressions.

A related question (possibly a digression) is, should there be a general convention for what kinds of names indices should have in practice? For example, for an index that numbers the words in a sentence, what's the best name? "word"? "words"? "position"? "sentence"?

2) This was discussed briefly in issue #2. I can reopen it if you would like to discuss it more.

**Comment by craffel** [comment]
I personally feel in the spirit of *named* tensors, it would be best if the axes had real-word names, even if they were made up (e.g. foo rather than i). (I guess technically "I" is an English word, but let's ignore that for the moment...)

**Comment by srush** [comment]
- I kind of agree with @craffel that we should use generic names in the informal section of the doc. It seems in the spirit to distinguish beyond just font and encourage good behavior. 

- My preference is that dims should be singular and evocative of physical space when possible => height, width, channel, batch are good standardized. For NLP, "word" is not great because it is ambiguous. I am okay with "time" although discretizing time is strange. "position" seems okay, that is relatively standard now. maybe "token"?

**Comment by srush** [comment]
* I am okay replacing colon. Equal would be the other choice, for instance Julia uses that for records. (The arguments about python confuse me a bit, since it seems to mirror python dict record syntax.)

**Comment by davidweichiang** [comment]
I see, the equations in question were in fact moved from the formal section to the informal section. They could be changed to use foo and bar, and/or use the actual example matrix A.

The question about "what makes a good name" is important enough that I will start a new issue about it.

**Comment by davidweichiang** [comment]
OK to close this?
