### ISSUE TITLE
Names with annotations

### ISSUE THREAD

**Issue by boazbk** [namedtensor/notation#14]
I think that in code, identifiers should be thought of as types, and while full on type theory might be too much for paper notation, it might still be good to treat them more than just pieces of text.

Since GitHub is such terrible math support, I wrote this using hackmd.io 
https://hackmd.io/@boazbk/S1YvQpwoD

**Comment by davidweichiang** [comment]
The proposal to treat 'batch' as a set roughly corresponds with #10 (right?). Can discussion of that piece of the proposal continue there?

**Comment by ekshaks** [comment]
Happy to see `DIDs` :) I had some related discussions earlier with @davidweichiang and @srush.

How about defining a DID to be an abstract datatype with 2 fields: `(name, expression)`. Here `expression` has standard grammar with size symbols and constants as terminals. Then, we define equivalence of DIDs, an algebra on top of it and how operators on DIDs work, matching, broadcasting.

I think this may allow us to handle many issues with duplicate names, splitting DIDs etc

**Comment by davidweichiang** [comment]
If I'm not mistaken, one consequence of your definitions is that if A has shape {foo:100} then you would allow A_{foo=12,bar=34} and the bar=34 would simply be ignored. I understand that you did this to simplify broadcasting, but allowing an explicit index to be ignored seems surprising.

I think the main point of your proposal is elsewhere, so if you think this point is worth discussing, could you create a new issue for it?

**Comment by davidweichiang** [comment]
The last piece of the proposal is on "DID annotations." Do you want to keep discussion of that piece in this issue?

**Comment by boazbk** [comment]
Sure. I can create another issue for non existing indices. Maybe before we talk about DID notation, we can see if people are comofortable with this.
