### ISSUE TITLE
Non existing indices

### ISSUE THREAD

**Issue by boazbk** [namedtensor/notation#15]
I propose that indexing over a non existing dimensions will do nothing.

That is, if for example a tensor T has (width,height) dimensions, and we use T_{batch=1} then this will simply be the same as T.

The main reason for this is that for notation in writing papers, there is no reason not to allow something unless it is ambiguous. If an author chooses write something like that (probably not exactly that  but could be in summations etc) then it would be clear for the reader what's the only sensible interpretation.

This is also the natural thing that happens if we want to do broadcasting,  so for example if we have  a (width,height,batch) tensor T and want to subtract out the average image we will write this as T - E_{b \in batch} T_b  or simply T - E_{batch} T

Now if we define T - Q as sum_{x,y,b in (width,height,batch) T_{x,y,b}  - Q_{x,y,b} then the above simply works even though E_{batch} T   does not have the batch dimension and so we don't have to define a special broadcasting rule for the + and - operations.

**Comment by davidweichiang** [comment]
Do you know of any situation where this would be useful (other than in defining how broadcasting works, where it's clearly useful)?

**Comment by boazbk** [comment]
Good question - I have to think about it

**Comment by srush** [comment]
I'm going to close this one. Even if we need this for the math, I don't think we should let the users see it. Size 1 dimensions in numpy feels intuitively broken to me.
