### ISSUE TITLE
Axis name under/beside 

### ISSUE THREAD

**Issue by craffel** [namedtensor/notation#3]
Sometimes the axis name appears under the operation; sometimes it appears beside it, e.g. key vs. time here:
![image](https://user-images.githubusercontent.com/417568/100921130-1ec14780-34aa-11eb-8b4e-71f4fe4eae00.png)
I think this makes it a little harder to read; any reason not stipulate that it's always "under"?

**Comment by davidweichiang** [comment]
This is LaTeX's standard behavior, which we could indeed change. I was especially surprised at the equation for the multivariate normal, where LaTeX decided to do it two different ways in one fraction.

I assume the rationale for putting it on the side is to keep formulas from getting too tall. This is especially true for inline formulas, where putting the subscript underneath would require uneven line spacing.

**Comment by srush** [comment]
I found this strange at first too. Maybe we should try looking at some text inline examples to get a sense of whether  "always underneath" would look really bad.
