### ISSUE TITLE
Expressing summing along an axis

### ISSUE THREAD

**Issue by azpoliak** [namedtensor/notation#30]
Would it make sense to refer to this in English as *summing A over the foo axis*?

https://github.com/namedtensor/notation/blob/76988af5cf7c6720cf2f7ee61b4fbc587f8d012a/main.tex#L171-L178

**Comment by srush** [comment]
Yeah I like "over". Since our names are always "wholes" you could probably say "summing over the foo". 

* summing over the channels
* summing over the seq
* summing over the vocab 

Doesn't always work. "summing over the hidden axis" is better.

**Comment by azpoliak** [comment]
great! I'll add a pr with that in the text shortly

**Comment by srush** [comment]
well let's wait for @davidweichiang to weigh in. We thought carefully about axis nouns, let's do the same for prepositions :)

**Comment by azpoliak** [comment]
Sgtm

**Comment by davidweichiang** [comment]
Sure, that sounds fine to me. The other usage I see in the NumPy/PyTorch documentation is "along the foo axis."

**Comment by srush** [comment]
I think I prefer "over" since it is less geometric. "summing over the vocab" sounds better to me than "summing along the vocab axis". The first seems to imply a space whereas the second seems to be a physical axis.

**Comment by azpoliak** [comment]
Good timing. The PR uses "over" instead of "along" or "across"
