### ISSUE TITLE
Quick examples section

### ISSUE THREAD

**Issue by srush** [namedtensor/notation#34]
I wonder if we should just have a section like this as well?

https://rockt.github.io/2018/04/30/einsum

I know everything is covered already, but that is a nice formatting.

**Comment by davidweichiang** [comment]
See 3.1.2 -- did you mean something like that?

**Comment by srush** [comment]
Yeah, that looks good. There is something nice about the formatting though of this post. Maybe because it has the sum form right next to the einsum form?

**Comment by davidweichiang** [comment]
We could show in parallel columns the equivalent expressions in matrix and/or index notation.

**Comment by srush** [comment]
I think that would be nice. Maybe just index notation?
