### ISSUE TITLE
What makes a good name?

### ISSUE THREAD

**Issue by davidweichiang** [namedtensor/notation#4]
In #1 we started to discuss what kinds of words names ideally should be. It seems to me that there are typically up to four choices:

- foo:i means "the i'th foo"
- foo:i means "the i'th thing in the foo"
- foo:i means "the thing that has a foo of i"
- foo:i mean "the i'th thing in the thing that has a foo of n"

Example: words in a sentence

- word:i means "the i'th word"
- sent:i means "the i'th word in the sentence"
- pos:i means "the word that has a position of i"
- len:i means "the i'th word in the sentence with length n"

Example: sentences in a minibatch

- sent:i means "the i'th sentence"
- batch:i means "the i'th sentence in the minibatch"
- ?
- batchsize:i means "the i'th sentence in the minibatch of size n"

The current document uses all four of these styles, if I'm not mistaken. And you can see that there's a danger because "sent" appears twice in the above examples.

Maybe there are more styles that I missed, too.

**Comment by srush** [comment]
This is such a good description of the problem. 

To make it more complex, I also think there is a difference in available words between countable / uncountable quantities. For a dimension like `height`, there isn't really a word for "the discretization of the 6th region of 10" so the only option is 4 "the i'th thing in the thing that has a foo of n". Conversely is it even appropriate to use `time` to refer to the "sixth bpe token out of 10".

**Comment by davidweichiang** [comment]
Actually I think 'height' has two meanings: you can say that a bird builds its nest at a height of 100 meters, which is the third option. I think 'time' is also the third option.

**Comment by davidweichiang** [comment]
'width' has to be the fourth option, though. And the fourth option makes the least sense to me.

- col:i means "the i'th column"
- horiz:i means "the i'th column in the horizontal direction" ?
- horiz:i means "the column that has a horizontal position of i" ?
- width:i means "the i'th column in the image that has a width of n"

**Comment by srush** [comment]
Option 2 is like the word "basis vector" option? That's kind of how I think of it.

**Comment by srush** [comment]
Categorical cases are interesting too. Only option 1 or 4 works since there is no order. i.e. class (option 1) or vocab (option 4)

**Comment by davidweichiang** [comment]
I think the high-order bit is whether the name should relate to the part or the whole, because that's where ambiguity can arise (like the 'sent' example above). The other distinctions might not matter as much.

**Comment by davidweichiang** [comment]
Going through the examples in the doc:
- time (3)
- key, val (2)
- head (1)
- emb (2? the meaning of "embedding" has shifted)
- state (1 or 2 depending on how you view RNNs)
- input, hidden, output (2)
- batch (2)
- channel (1)
- vocab (2)
- class, cluster (1)
- row, col (1)
- assign (2?)
- height, width (4)
- d, dim (1?)

**Comment by srush** [comment]
I agree with your distinction. 

The problem in my mind is there is just not enough "part words" for (1) to really work. If we pluralize channel, class, cluster, head and just say that height, width, time, key, val, are "whole words" then things work.

**Comment by srush** [comment]
I guess in particular I don't know what the part of a `hidden, key, val, depth, input` could possibly be.

**Comment by davidweichiang** [comment]
I don't mind recommending that indices be named after wholes, but I do feel that issue #2 is going in the opposite direction: 'batch=1' really feels like 'the first batch' to me, not 'the first sentence in the batch.'

**Comment by srush** [comment]
I wrote the following to my colleagues in vision 

"Can you guys help me with this extremely silly vision question? Its really bothering me. Imagine I have a magic chunk operator © 

Swarm © bee
Sentence © token
Batch © example
Time series © frame
Spectrum © coefficient
Height © ?
Width © ?
Depth © ?
"

They said this question is total nonsense and wouldn't even justify it with a response. I don't think they even think about these as discrete parts. (I suggested hightile, widtile, and deptile.  They did not appreciate)

What would be better notation for batch=1 ? We could do batch[1]? It sounds like we want to convey restriction not matching?

**Comment by davidweichiang** [comment]
How about this way of thinking about it: How would you write a struct that locates a word in a list of sentences?

```
struct {
    int sent;
    int word;
};
```

How would you write a struct that locates a pixel in an image?

```
struct {
    int x;
    int y;
};
```

I am totally ignorant about CV, though, and don't know what depth is -- is that for 3D? Or for color?

**Comment by srush** [comment]
That is a compelling argument. ( I still like `token` better than word though, since we would need `word` to replace `vocab` for embeddings. )

But what about hidden or embed? What does one of those even mean? I guess we could call them `feature` and use `in_feature` or `out_feature`? Also does `time` become `position` ?

(Maybe we can bless some canonical short names like feat, pos, x, y, z)

**Comment by davidweichiang** [comment]
OK, let me try arguing the other way: I was struck when replacing all the colons with equals (#8) that we talk very little about individual elements. It's in the formal definitions and in the definitions of all the reductions, but most examples do not do any indexing at all. So the more visible notation, by far, is $R^{width:100}$, not $A_{column=42}$. And when talking about sets of tensors, it makes more sense for names to name wholes. Nevertheless, I would hope for a better notation than $A_{width=42}$ -- even if it's rare, it just looks so strange to me.

**Comment by srush** [comment]
I'm fine with this conclusion. I tend to dislike plurals though . Maybe we can encourage collective nouns, span words when possible. (`vocab` versus `words`)
