### ISSUE TITLE
Norms 

### ISSUE THREAD

**Issue by srush** [namedtensor/notation#48]
There is a bug in the xnorm function. The norms are a bit more complex than we have them written. I will do a pass and fix.

**Comment by davidweichiang** [comment]
Oh, sorry (I guess I'll find out what the bug was)

**Comment by srush** [comment]
Oh sorry, wasn't trying to be mysterious, just haven't gone through the details yet. When going through the pytorch docs, I realized that the gamma shape doesn't necessarily line up with the mean and variance as you might expect.

**Comment by davidweichiang** [comment]
Any progress on this?

**Comment by srush** [comment]
no, sorry, I will get to it this weekend.
