### ISSUE TITLE
Index Maps / Delta's

### ISSUE THREAD

**Issue by srush** [namedtensor/notation#49]
I noticed that the conv1d now uses the "index map" style with the \delta function. While this is super convenient for the derivative, I think it makes the standard function a bit harder to read. Is there a way that could be defined in the old-style and then the index map becomes exposed as part of a derivative rule?

**Comment by davidweichiang** [comment]
Oh, I kind of liked it better this way, but if you want to change it back, I think you could write dU/dX_{seq(i),kern(j),seq*(k)} = \delta(k,i+j-1) and it would serve the same purpose as C.

Somewhat related, you don’t think it
would be helpful to define \star for cross-correlation and \ast for convolution?

**Comment by davidweichiang** [comment]
Like this:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/1399913/104029794-6b2e3000-5198-11eb-9be4-82bfdad886a0.png">

**Comment by srush** [comment]
This looks good to me. This captures the spirit of the delta contraction without while still allowing for direct indexing on the forward pass.
