### ISSUE TITLE
Range/assignment inconsistency

### ISSUE THREAD

**Issue by boazbk** [namedtensor/notation#5]
(The fact that GitHub doesn't support latex math is really annoying in this case)

In your notation, 3,5,6 in the definition tensor $A \in \mathbb{R}^{foo: 3,bar: 5, blah:6}$ stand for the length of each dimension, while when indexing $A_{foo:1,bar:2,blah:3}$, the $1,2,3$ stand for the indices of particular indices. I find this somewhat confusing. 

Also, as long as you are generalizing, you might want to allow tensors of the form $\mathbb{R}^{S \times T \times U}$ where $S,U,T$ are not necessarily intervals of integers. For example, maybe in some cases it may be easier to think of RGB as a single dimension that happens to be indexed by three numbers than as three separate dimensions.

One way to modify this is to write $A \in \mathbb{R}^{foo,bar,blah}$ and with a slight abuse of notation think of foo,bar,blah both as disjoint versions of the index sets and as function mapping the index set to these disjoint subsets. (So mathematically, even if we define $foo$ and $bar$ both as the set $[32]$ we think of them as disjoint versions of this set, say $foo = \{ 1_f, 2_f, \ldots, 32_f \}$ and $bar = \{ 1_b, 2_b ,\ldots, 32_b \}$ and we also think of them as functions where $foo(x) = x_f$ and $bar(y)=y_b$ for every $x,y \in [32]$.)

Something like $A \in \mathbb{R}^{batch,x,y,color}$ and a notation to define these sets such as  $batch := [128]$, $x ,y:= [32]$ and $color := [256]^3$

Then we can also use the standard convention that if we apply a function $bar$ to a set $A$ this corresponds to $\{ bar(a) | a\in A \}$ and so use not just  $A_{batch(5)}$ for the 5-th batch  (i.e., tensor taking x,y,color) but also  $A_{y([17,32])}$ for the bottom half of the image.

Another thing I would suggest is that to be consistent with math notation, use some way to highlight (maybe a bold version) when an operation involves broadcasting of inconsistent dimensions.

Finally, I think the issue with things like applying linear transformations on a coordinate etc is that sometimes the tensor really does act on the same type of indices. In such cases it would be natural to write $A \in \mathbb{R}^{state,state}$ and have the convention that at this point order matters. You could use then something like $A_{state(\cdot),state(4)}$ to show that you are fixing the column and leaving the row free.

**Comment by boazbk** [comment]
I guess I was assuming a one-hot encoding of colors which is not very natural, but I think the general point that sometimes dimensions need not be indexed by an interval of integers still holds

**Comment by davidweichiang** [comment]
These are all great points, and I think some of them are addressed or at least raised in the document.

- On sizes vs indices, this is being discussed in #2.
- On colors, I think we already have this. See https://namedtensor.github.io/#named-tensors.
- I didn't understand what was meant by inconsistent dimensions.
- On linear transformations, we don't have a settled answer yet. See https://namedtensor.github.io/#duality.

**Comment by boazbk** [comment]
I should say that I am coming from a mostly TCS/math background and a bit of ML theory perspective, and so my main interest is that notation is readable by mathematicians and so it's as compatible as possible with standard math. 

* Thanks

* Colors was a bad example but the point I wanted to make is that in general the index need not be a number. For example, if V is a matrix corresponding to an embedding of words embedding then the natural way to write the embedding of "house" could be  $V_{word:"house"}$ or $V_{word("house")}$ - the word dimension should be thought of as being indexed by words 

* By inconsistent dimensions I just meant that in terms such as $A + 1$ that would be considered inconsistent in a math paper (since you are adding a scalar to a number) it could be nice to use a bold + or something that indicates that you are using broadcasting.

* I think the issue here is not linear transformation per se, but accounting for the fact that sometimes matrices/tensors have different dimensions that are  of the same type and so different indices could be considered interchangeable

**Comment by davidweichiang** [comment]
- On colors (which I think is a fine example), a shape is defined as a mapping from names to sets, and the set can either be a numeric range (e.g., [100], which we write as 100) or it can be a set of other objects like {red, green, blue} or the vocabulary of English. So I think the machinery is all in there to do what you're suggesting, although there are no examples of this in the document. Maybe there should be.

- You're not the first person to tell us that broadcasting is surprising in math notation, and I think it would be interesting to think about notation that makes it more explicit. Like $A + [1]_{broadcast(foo,bar}}$ except more succinct?

- We did have a variant at one point where a tensor could have multiple indices with the same name. But people didn't seem interested in it, so I discarded it. I'd be curious to see use cases for this idea.

**Comment by boazbk** [comment]
I would suggest that in the document you use i:[5] rather than i:5 (or if you replace colon with blah then use the notation name blah set ). This also has the advantage that if a paper wants to use zero based indexing they can just define [k] as the set {0,1,...,k-1}

**Comment by davidweichiang** [comment]
Yeah, I had that in the original version (you can see it in https://twitter.com/davidweichiang/status/1331682023057088513) and it's still there in the formal definitions, available for anyone to use if they want to.

But I think that fluidity between n and [n] has precedent in existing math notation. We write X^Y for the set of functions from Y to X, and the notations 2^X, X^n, and X^{m × n} can all be interpreted as instances of X^Y if we see them as shorthand for [2]^X, X^[n], and X^{[m] × [n]}.

At any rate, I think it would be completely consistent with our definitions if someone redefined [n] = {0, ..., n-1} and then defined their tensors as, e.g., R^{foo:[100]}.

**Comment by boazbk** [comment]
You are right about fluidity between number n and the set [n].

**Comment by davidweichiang** [comment]
OK to close this? I think the main issue in the issue title is the same as #2, and the others were either addressed or spun off into their own issues. Possibly we can start another issue about names versus types.
