### ISSUE TITLE
Definition of outer product

### ISSUE THREAD

**Issue by bayerj** [namedtensor/notation#54]
The outer product is defined using the contraction operator:

![Screenshot 2021-01-21 at 20 52 03](https://user-images.githubusercontent.com/50352/105404725-969a2b80-5c2a-11eb-91a3-26160c1cf485.png)

From my understanding of the second paragraph in 2.1, each of the two factors **u_ax1(i)** and **x_ax2(j)** in the sum should be a scalar. That is because a vector is indexed. Now, multiplying two scalars yields a scalar, and summing many scalars also yields a scalar. The whole expression should hence be a scalar. The outer product should be a matrix though.

I can see how the broadcasting rules could somehow then span the matrix. This would be the case if the indexing did not return scalars, but vectors with a named axis of size 1. Is this what you envision to happen here?

PS: Great idea!

**Comment by davidweichiang** [comment]
Thanks, you're right that there must be a bug here -- will fix!
