### ISSUE TITLE
Typo in vector dot-product

### ISSUE THREAD

**Issue by BBischof** [namedtensor/notation#56]
It seems there is a typo here:

![image](https://user-images.githubusercontent.com/5480181/107870796-6cfea980-6e50-11eb-896c-96525b4693f3.png)

I think you want the product inside the summation to also be C_width.

I expected the error to be on this line:
https://github.com/namedtensor/notation/blob/a0e3be292dcfd63ed1c24d88bce5b8daf4d31839/main.tex#L183

...however I can't quite sort out your LaTeX magic to see what's causing the issue. I see that `x` and `y` are evaluating to matrix names, but I can't spot the issue here.

**Comment by davidweichiang** [comment]
Thanks! I'll fix it.

**Comment by davidweichiang** [comment]
Oh, I think it's because the tex and pdf are out of sync. I'll just push the latest pdf.
