### ISSUE TITLE
Should broadcasting be explicit?

### ISSUE THREAD

**Issue by davidweichiang** [namedtensor/notation#7]
This is a spin-off from #5. Is broadcasting too magical for math notation, and if so, what would be a good way to write it?

**Comment by srush** [comment]
I'm worried about this as well. 

What if we allow tensor contract broadcasting (join) since that seems matmul like, but disallow hadamard and + / broadcasting? 

The main time that I use broadcasting is reduce and then apply such as for normalization. If we had notation for reduce but keep dims that might work?

**Comment by boazbk** [comment]
I think even something very light like a dot or bold on top of the operator would be useful just to let a reader from math know broadcasting is happening (or at least that something nonstandard is happening).

A significant advantage of named tensors is that they make broadcasting less magical. For example if you try to add a (1,3) shaped vector to a (3,3,3) tensor then it's not intuitively clear which way you'll lift the vector, but if you only broadcast when the name of the 3 shaped dimension of the vector matches the name of one of the dimensions of the tensor then it is clear what you'll do.

**Comment by davidweichiang** [comment]
How about (optionally?) writing the names of broadcasted indices above the operator?

<img width="161" alt="image" src="https://user-images.githubusercontent.com/1399913/101076159-fbad9b00-3570-11eb-8571-c30e000ee731.png">

In most cases, a name below an operator means "eliminate this name" and a name above an operator means "keep this name"?

**Comment by davidweichiang** [comment]
(But my preference would still be to do nothing.)

**Comment by srush** [comment]
I think we can close this one. Without broadcasting, a lot of this stops being fun.
